"""empty message

Revision ID: e653fbda8c69
Revises: 5e8a6b1137e1
Create Date: 2019-11-18 14:38:02.954134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e653fbda8c69'
down_revision = '5e8a6b1137e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'user_id',
                    existing_type=sa.INTEGER())
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'user_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###
